services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: "5432"

      REDIS_HOST: redis
      REDIS_PORT: "6379"

      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_TICKET_INDEX: tickets

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


  db:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/full_setup.sql:/docker-entrypoint-initdb.d/01_full_setup.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


  elasticsearch:
    image: elasticsearch:9.5.1

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s


volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: